Input from a tty

./main.x:   rice@storm.stanford.edu   Thu Jul 21 14:17:34 2016
		sets next: in="/scr1/rice/3D_junk.H@"
		From par: verbose=yes
		From par: qfact=200
		From par: w0=60
		From par: depth=0
		From par: src_z=0
		From par: src_y=10
		From par: timeBlocks=40
		From par: maxF=80
		From par: bound=20
		From par: error=20
		From par: errorFact=1.2
		From par: qfact=200
		From par: downfact=0.04
		From par: jimage=6
		From par: slow=0
		From par: qtest=yes
		From par: writeSection=-1
		From par: writeCheckpoint=-1
