Input from a tty

Wavelet:   rice@storm.stanford.edu   Thu Jul 21 14:17:27 2016
		sets next: in="/scr1/rice/3D_source.H@"
		n2=1
		n3=1
		o1=0
	Wavelet generation
		esize=4
		ascii="n"
		given n1=128
		d1=0.001
		n1=128
		domain="time"
		n1wavelet=128
		d1wavelet=0.001
		domainwavelet="time"
		wavelet="ricker2"
		phase="none"
		degrees=0
		fund=40
		flow=10
		fhigh=60
		order=6
		orderlow=6
		orderhigh=6
		tdelay=0.02
		bell=0.032
		boxcar=0.128
		data_format="xdr_float"

