/* This file is automatically generated. DO NOT EDIT! */

#ifndef _fastmarch_h
#define _fastmarch_h


#include <rsf.h>


void fastmarch_init (int n3,int n2,int n1);
/*< Initialize data dimensions >*/


void fastmarch (float* time                /* time */, 
		float* v                   /* slowness squared */, 
		int* in                    /* in/front/out flag */, 
		bool* plane                /* if plane source */,
		int   n3,  int n2,  int n1 /* dimensions */,
		float o3,float o2,float o1 /* origin */,
		float d3,float d2,float d1 /* sampling */,
		float s3,float s2,float s1 /* source */,
		int   b3,  int b2,  int b1 /* box around the source */,
		int order                  /* accuracy order (1,2,3) */);
/*< Run fast marching eikonal solver >*/


void fastmarch_close (void);
/*< Free allocated storage >*/

#endif
