import os
Import('*')

cuda_bin_list = [
    ("elastic", "Mewefd3d_gpu_p2p.cu"),
    ("maketime", "main-maketime.c"),
    ("interp", "sin2.c"),
    ("cuInterp", "Minterp.cu"),
]

cuda_module = """
fdutil.c
vel.c
box.c
resample.c
check.c
fastmarch.c
ewefd3d_kernels.cu
interpfunc.c
""".split()

include_dir = [
]

depend_libpath = []
depend_libs = []

mycudaenv = cudaenv.Clone(CPPPATH = include_dir)
mycudaenv.Append(LIBPATH = depend_libpath)
mycudaenv.Append(LIBS = depend_libs)
cudaobjs = mycudaenv.StaticObject(cuda_module)

for bin in cuda_bin_list:
  bin_obj = mycudaenv.StaticObject(bin[1])
  bin_target = mycudaenv.Program(target = bin[0], source = bin_obj + cudaobjs)
  mycudaenv.Install("#" + dirs['bin'], bin_target)
